# -*- coding: utf-8 -*-
"""Task_MongoDB.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DyVaLxypD-CmMWd_cewBClPJRXGY8jLC

#**Lista de Exercicios**

---

Lista feita no MongoDB Compass

###Questão A

Exibir todos os documentos da coleção restaurantes
"""

{}

"""###Questão B

Exibir chaves restaurant_id, name, borough e cuisine
"""

{"restaurant_id" : 1,"name":1,"borough":1,"cuisine" :1}

"""###Questão C

Similar ao anterior, mas remover da exibição a chave _id
"""

{"restaurant_id": 1, "name": 1, "borough": 1, "cuisine": 1, "_id": 0}

"""###Questão D

Exibir restaurantes no bairro Bronx
"""

{"borough": "Bronx"}

"""###Questão E

Exibir 5 restaurantes no bairro Bronx

limit: limita a quantidade da busca.

No mongodb compass tem uma janela chamada limit, nela foi colocada o valor 5.
"""

{"borough": "Bronx"}

"""###Questão F

Exibir os próximos 5 restaurantes no bairro Bronx, após ter pulado os 5 primeiros

skip: pula as informações

Foi atribuido o valor 5 as janelas skip e limit
"""

{"borough": "Bronx"}

"""###Questão G

Exibir restaurantes com score > 90
"""

{"grades.score": { $gt: 90 }}

"""###Questão H

Exibir restaurantes com score entre 80 e 100, inclusive
"""

{"grades.score": { $gte: 80, $lte: 100 }}

"""###Questão I

Explique o critério de busca do comando abaixo:

**Resposta:** Ele vai no banco e busca todas as cozinhas que não forem Americanas com as pontuações maiores que 70 e com as coordernadas menores que -65.754168.

###Questão J

Exibir restaurantes que não preparam cozinha americana e tiveram grade point
A que não estão no Brooklin. Exibir resultado com a cozinha ordenada
decrescente
"""

{"cuisine": { "$ne": "American" },
 "grades": { "$exists": true, "$not": { "$size": 0 } },
 "borough": { "$ne": "Brooklyn" }}

"""Em sort é colocado: {"cuisine": -1} para ordenar em ordem decrescente"""

{"cuisine": -1}

"""###Questão K

Exibir restaurantes com ‘Wil’ nas três primeiras letras do nome
"""

{"name": { $regex: /^Wil/i }}

"""###Questão L

Exibir restaurantes com ‘ces’ nas três últimas letras do nome
"""

{"name": { "$regex": /ces$/i }}

"""###Questão M

Exibir restaurantes com ‘Reg’ em algum lugar do nome
"""

{"name": { $regex: /Reg/i }}

"""###Questão N

Exibir restaurantes no Bronx que preparem ou cozinha americana ou chinesa
"""

{"borough": "Bronx", "cuisine": { "$in": ["American", "Chinese"] }}

"""###Questão O

Exibir restaurantes por nome de cozinha em ordem alfabética ascendente e, para
esta mesma cozinha, o bairro do restaurante em ordem descendente

Em sort é colocado: { "cuisine": 1, "borough": -1 } para os nomes das cozinhas ficarem em ordem alfabética ascendente e com os bairros do restaurante na ordem descrescente.
"""

{"cuisine": 1, "borough": -1}

"""###Questão P

Exibir restaurantes onde a chave endereço da cozinha existe
"""

{"address": { "$exists": true }}